paths:
  '/inventories/{id}/update':
    summary: decrease stock operation on inventories
    put:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  description: productId of this DecreaseStock
                  type: integer
                qty:
                  description: qty of this DecreaseStock
                  type: integer
            examples:
              Example 0:
                value:
                  productId: 123
                  qty: 10
              Example 1:
                value:
                  productId: 456
                  qty: 20
              Example 2:
                value:
                  productId: 789
                  qty: 50
      parameters:
        - name: id
          description: DecreaseStock name
          schema:
            type: integer
          in: path
          required: true
          examples:
            Example 0:
              value: 123
            Example 1:
              value: 456
            Example 2:
              value: 789
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
              examples:
                Example 0:
                  value:
                    stock: 40
                    productId: 123
                Example 1:
                  value:
                    stock: 80
                    productId: 456
                Example 2:
                  value:
                    stock: 150
                    productId: 789
          description: DecreaseStock Operation
      operationId: DecreaseStock
      summary: DecreaseStock
      description: DecreaseStock
  /inventories/search/findInventory:
    summary: findInventory query on inventories
    get:
      parameters:
        - name: name
          description: Name
          schema:
            type: integer
          in: query
          required: false
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
              examples:
                '1':
                  value:
                    productId: 1
                    stock: 1
          description: FindInventory Query
      operationId: FindInventory
      summary: FindInventory
      description: FindInventory
  /inventories:
    summary: Global operations on inventories
    get:
      tags:
        - inventories
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Inventory'
              examples:
                inventories_json:
                  value:
                    - productId: 1
                      stock: 1
          description: Get list of inventories
      operationId: GetInventory
      summary: Get list of inventories
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Inventory'
            examples:
              '1':
                value:
                  productId: 1
                  stock: 1
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
              examples:
                '1':
                  value:
                    productId: 1
                    stock: 1
          description: Changed Inventory
      operationId: Post Inventory
      summary: Post Inventory
  '/inventories/{id}':
    summary: Specific operation on inventories
    get:
      parameters:
        - examples:
            '1':
              value: 1
          name: id
          description: Inventory name
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
              examples:
                '1':
                  value:
                    productId: 1
                    stock: 1
          description: inventories with specified id
      operationId: GetInventoryById
      summary: Get Inventory by id
      description: Get Inventory by id
    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Inventory'
            examples:
              '1':
                value:
                  productId: 1
                  stock: 1
        required: true
      parameters:
        - examples:
            '1':
              value: 1
          name: productId
          description: Inventory name
          schema:
            type: integer
          in: path
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Inventory'
              examples:
                '1':
                  value:
                    productId: 1
                    stock: 1
          description: Changed Inventory
      operationId: PatchInventory
      summary: Patch existing Inventory
    parameters:
      - name: id
        description: Inventory id
        schema:
          type: integer
        in: path
        required: true
openapi: 3.0.2
info:
  title: Inventory
  version: 0.0.1
  description: API definition of inventory
  contact:
    name: creator's name
    url: 'http://creator.homepage.address'
    email: creator@creator.com
  license:
    name: MIT License
    url: 'https://opensource.org/licenses/MIT'
components:
  schemas:
    Inventory:
      title: Root Type for Inventory
      description: The root of the Inventory type's schema.
      type: object
      properties:
        productId:
          description: productId of this Inventory
          type: integer
        stock:
          description: stock of this Inventory
          type: integer
      example:
        productId: 1
        stock: 1
tags:
  - name: Inventory
    description: Inventory resource
